apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-strict-mtls
  namespace: istio-system
spec:
  # Applying this to istio-system makes it a GLOBAL rule for the whole mesh
  mtls:
    mode: STRICT