apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-canary
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {} # Pauses the rollout until we explicitly say "continue"
      - setWeight: 50
      - pause: {duration: 10s} # Automatically continues after 10 seconds
  selector:
    matchLabels:
      app: demo-canary
  template:
    metadata:
      labels:
        app: demo-canary
    spec:
      containers:
      - name: web
        image: nginx:1.24-alpine
