apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sys-kong
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    targetRevision: 2.38.0  # <--- Put the version back
    chart: kong             # <--- Change this from 'ingress' to 'kong'
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true