apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sys-kong
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    targetRevision: 2.38.0
    chart: kong
    helm:
      parameters:
        # 1. Strip out the AWS annotations
        # 2. Tell Kong to only create an internal IP
        - name: proxy.type
          value: "ClusterIP"
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true